spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?userSSL=flase
        username: root
        password: daokhanh3920




    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

#JPA settings
    jpa.hibernate.ddl_auto: create